---
# Thanks, Sven, for these amazing instructions!
# https://finestructure.co/blog/2020/11/27/running-docker-on-apple-silicon-m1

# This can take over a minute to to complete if 'docker context rm' is used if the
# underlying VM was deleted before this playbook was run.
- name: Delete old logs
  file:
    path: "{{ stage_dir }}/{{ item }}"
    state: absent
  with_items:
    - screenlog.0
    - vm.log

- name: Remove stale Docker contexts
  command: sh -c "grep -r 'docker-arm64' ~/.docker/contexts | cut -f1 -d ':' | xargs rm -f && sed -i '' 's/docker-arm64/default/' ~/.docker/config.json"

- name: Check for XCode Command Line Tools
  command: which xcodebuild
  register: xcode_cli_tools_result

- fail:
    msg: >-
      You don't have the XCode Command Line Tools installed.
      Run this to install them --- 'xcode-select --install'
  when: xcode_cli_tools_result.rc != 0

- name: Enable Command Line Tools
  command: sudo xcode-select --switch /Library/Developer/CommandLineTools
  
- name: Create mount directory
  file:
    path: /Volumes/Ubuntu
    state: directory

- name: Create staging directory
  file:
    path: "{{ stage_dir }}"
    state: directory

- name: Copy provisioning scripts
  copy:
    src: "{{ item }}"
    dest: "{{ stage_dir }}/{{ item }}"
    mode: 0755
  with_items:
    - provision.sh
    - data_provision.sh
    - add_private_key.sh

- name: Are we mounted?
  command: sh -c "/sbin/mount | grep -q Ubuntu"
  ignore_errors: true
  register: mounted_result

- set_fact:
    mounted: "{{ mounted_result.rc == 0 }}"

- name: Did we download the Live CD already?
  command: test -e "{{ vm_iso_local_fp }}"
  ignore_errors: true
  register: live_cd_present

- name: Did we download and compile vftool already?
  command: test -e "{{ vftool_path }}"
  ignore_errors: true
  register: vftool_present

- name: Did we already create a keypair?
  command: test -e "{{ ssh_key_pubkey_path }}"
  ignore_errors: true
  register: ssh_key_present

- name: Did we already create the Docker data volume?
  command: test -e "{{ docker_data_path }}"
  ignore_errors: true
  register: docker_data_path_present

- name: Did we already create the Docker user data volume?
  command: test -e "{{ docker_userdata_path }}"
  ignore_errors: true
  register: docker_userdata_path_present

# Unfortunately, Apple's virt framework doesn't support thin-provisioned volumes
# like Hyperkit et. al. do. This means we need to thick-provision everything
# upfront. This reduces the total amount of space we can allocate to dockerd/
# containerd, as too much will unnecessarily consume disk space on the host
# whereas not enough will trigger ENOSPC too often.
#
# Thick-provisioned volumes do tend to perform better since space inflation doesn't
# need to occur on-write. This combined with rsync for volume synchro should provide
# a decent user experience.
- name: Create 32GB Docker data volume (this will take about a few minutes)
  command: "dd if=/dev/zero of={{ docker_data_path }} bs=1024 count=32000000"
  when: docker_data_path_present.rc != 0

- name: Create 8GB Docker user-data volumes (this will take about a minute)
  command: "dd if=/dev/zero of={{ docker_userdata_path }} bs=1024 count=8000000"
  when: docker_userdata_path_present.rc != 0

- name: Create a SSH keypair for this host
  command: ssh-keygen -t rsa -f "{{ ssh_key_path }}" -q -N ""
  when: ssh_key_present.rc != 0

- name: Permission the key
  when: ssh_key_present.rc != 0
  file:
    path: "{{ ssh_key_path }}"
    mode: 0600

- name: Save the public key as a variable
  set_fact:
    pubkey: "{{ lookup('file', ssh_key_pubkey_path) }}"

- name: Download Live CD
  get_url:
    url: "{{ vm_iso_url }}"
    dest: "{{ vm_iso_local_fp }}"
  when: not mounted and live_cd_present.rc != 0

- name: Download vftool
  git:
    repo: "{{ vftool_url }}"
    dest: "{{ vftool_dir }}"
  when: vftool_present.rc != 0

- name: Force vftool to build as ARM64 executable
  command: sh -c "sed -i '' 's/^CFLAGS.*/CFLAGS= -O3 -arch arm64/' {{ vftool_dir }}/Makefile"

- name: Compile vftool
  command: sh -c "cd {{ vftool_dir }} && make"

- name: Attach the ISO to the staging directory
  command: hdiutil attach -nomount "{{ vm_iso_local_fp }}"
  register: attach_result
  when: not mounted

- set_fact:
    device_number: "{{ attach_result.stdout_lines[0].split(' ')[0] }}"
  when: not mounted

- name: Mount the image locally
  command: /sbin/mount -t cd9660 "{{ device_number }}" /Volumes/Ubuntu
  when: not mounted

- name: Get kernel image
  copy:
    src: "/Volumes/Ubuntu/casper/{{ item.name }}"
    dest: "{{ stage_dir }}/{{ item.path }}"
  with_items:
    - name: vmlinuz
      path: vmlinuz.gz
    - name: initrd
      path: initrd

- name: Unzip kernel
  command: sh -c "cd "{{ stage_dir }}" && { test -e vmlinuz || gunzip {{ stage_dir }}/vmlinuz.gz; }"

- name: Start the VM daemonized
  command: "sudo sh -c '( ( nohup {{ vftool_path }} -p 4 -k {{ stage_dir }}/vmlinuz -i {{ stage_dir }}/initrd -c {{ vm_iso_local_fp }} -d {{ docker_data_path }} -d {{ docker_userdata_path }} -m 4096 -a console=hvc0 &>{{ stage_dir }}/vm.log ) & )'"

- name: Wait for a fd to become available
  command: "sh -c 'grep \"Waiting for connection to\" {{ stage_dir }}/vm.log'"
  register: tty_result
  until: tty_result.rc == 0
  retries: 5
  delay: 1

- name: Get the TTY for the VM
  command: "sh -c 'grep \"Waiting for connection to\" {{ stage_dir }}/vm.log | sed \"s#.*/dev#/dev#\"'"
  register: tty_result

- debug:
    msg: "found: {{ tty_result.stdout }}"

- set_fact:
    tty: "{{ tty_result.stdout }}"

- name: Create a new screen session
  command: "sh -c '( ( cd {{ stage_dir }} && nohup screen -dmS {{ session_name }} -L - {{ tty }}; sleep 1 &>screenlog.0 ) & )'"
  
- name: Verify that a session was created
  command: "sudo sh -c 'screen -ls | grep {{ session_name }}'"
  register: result
  until: result.rc == 0
  retries: 3
  delay: 1

- name: Wait for Ubuntu login
  command: "sudo sh -c 'grep \"login:\" {{ stage_dir }}/screenlog.0 | awk \"{print $NF}\"'"
  register: tty_result
  until: '"login:" in tty_result.stdout'
  retries: 30
  delay: 1

- name: Login
  command: "sudo sh -c 'screen -S {{ session_name }} -p 0 -X stuff $(printf \"ubuntu\\r\\n\")'"

- name: Wait for prompt
  command: "sudo sh -c 'grep \"ubuntu@ubuntu:\" {{ stage_dir }}/screenlog.0'"
  register: tty_result
  until: tty_result.rc == 0
  retries: 30
  delay: 1

- name: Provision the file system on the Docker data dir
  command: "{{ stage_dir }}/data_provision.sh {{ session_name }} {{ lookup('env', 'HOME') }}"
  when: docker_data_path_present.rc != 0 and docker_userdata_path_present.rc != 0
  delay: 3

- name: Wait for data provision to finish
  when: docker_data_path_present.rc != 0 and docker_userdata_path_present.rc != 0
  command: sh -c "grep 'data provision finished' {{ stage_dir }}/screenlog.0"
  register: data_provision_result
  until: data_provision_result.rc == 0 and data_provision_result.stdout != ""
  retries: 15
  delay: 1

- name: Provision the machine
  command: "{{ stage_dir }}/provision.sh {{ session_name }} '{{ lookup('env', 'HOME') }}'"

- name: Get IP address
  command: sh -c "grep 'inet 192.168' {{ stage_dir }}/screenlog.0 | awk '{print $2}'"
  register: ip_address_result
  until: ip_address_result.rc == 0 and ip_address_result.stdout != ""
  retries: 240
  delay: 1

- name: Add our private key
  command: "{{ stage_dir }}/add_private_key.sh {{ session_name }} {{ ssh_key_pubkey_path }}"

- set_fact:
    ip_address: "{{ ip_address_result.stdout }}"

- debug:
    msg: "stdout -> {{ ip_address_result.stdout }}, address -> {{ ip_address }}"

- name: Create a Docker context for this VM
  command: docker context create docker-arm64 --docker "host=ssh://ubuntu@{{ ip_address }}"

- name: Set the context to default
  command: docker context use docker-arm64

- name: Give user rwx permissions to stage dir
  file:
    path: "{{ stage_dir }}"
    mode: 0755
    owner: "{{ lookup('env', 'USER') }}"
    recurse: yes

- name: Give user rwx permissions to key
  file:
    path: "{{ ssh_key_pubkey_path }}"
    owner: "{{ lookup('env', 'USER') }}"
  with_items:
    - "{{ ssh_key_pubkey_path }}"
    - "{{ ssh_key_path }}"

- name: Give user rw permissions to Docker directory
  file:
    path: "{{ lookup('env', 'USER') }}/.docker"
    owner: "{{ lookup('env', 'USER') }}"
    recurse: yes

- debug:
    msg: >-
      "Docker is ready to use! To kill the underlying VM, simply run 'ansible-playbook kill.yml'.
      If you need to access the underlying VM, you can do so by either SSH-ing into it
      'ssh ubuntu@{{ ip_address }}' or running screen 'sudo screen -r {{ session_name }}'
